First step in adding documentation

diff --git a/doc/make_on_macos b/doc/make_on_macos
--- a/doc/make_on_macos
+++ b/doc/make_on_macos
@@ -1,4 +1,13 @@
 #!/bin/bash
+#
+# Wrapper script for calling make on macOS with a Homebrew installation.
+#
+# This is needed because the system ghostscript and texinfo are outdated.
+
+if ! which brew &>/dev/null; then
+  echo >&2 "Error: Homebrew is required but was not found."
+  exit 1
+fi
 
 PATH="$(brew --prefix ghostscript)/bin:$(brew --prefix texinfo)/bin:$PATH"
-make "$*"
+make "$@"
